version: '3.9'

volumes:
  ellipsis-hackathon-db-volume:
    name: ellipsis-hackathon-postgres-data

services:
  ellipsis-hackathon-db-service:
    image: postgres
    container_name: ellipsis-hackathon-db
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432
    volumes:
      - ellipsis-hackathon-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Secr3tPassw0rd123
      POSTGRES_DB: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
