# fly.toml app configuration file generated for ellipsis-aegis on 2024-08-23T20:14:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ellipsis-aegis'
primary_region = 'sin'

[build]
  dockerfile = '../Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
