name: Fly Deploy to Production
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_DIALECT: ${{ secrets.DB_DIALECT }}
  DB_PORT: ${{ secrets.DB_PORT }}
  BACKEND_TZ: ${{ secrets.BACKEND_TZ }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_DURATION: ${{ secrets.JWT_DURATION }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  SGID_CLIENT_ID: ${{ secrets.SGID_CLIENT_ID }}
  SGID_CLIENT_SECRET: ${{ secrets.SGID_CLIENT_SECRET }}
  SGID_PRIVATE_KEY: ${{ secrets.SGID_PRIVATE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STIPE_PUBLISHABLE_KEY: ${{ secrets.STIPE_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_BACKEND_URL: ${{ vars.BACKEND_URL }}
  FRONTEND_DOMAIN: ${{ vars.FRONTEND_DOMAIN }}
  BACKEND_DOMAIN: ${{ vars.BACKEND_URL }}
  VERSION: ${{ vars.VERSION }}

jobs:
  deploy-frontend:
    name: Deploy frontend app
    environment: production
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy \
      -c ./apps/frontend/.fly/fly.toml \
      --build-arg NEXT_PUBLIC_BACKEND_URL="${NEXT_PUBLIC_BACKEND_URL}" \
      --build-arg STIPE_PUBLISHABLE_KEY="${STIPE_PUBLISHABLE_KEY}" \
      --local-only .

  deploy-backend:
    name: Deploy backend app
    environment: production
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy \
            --env DB_PASSWORD="${DB_PASSWORD}" \
            --env DB_HOST="${DB_HOST}" \
            --env DB_NAME="${DB_NAME}" \
            --env DB_USER="${DB_USER}" \
            --env DB_DIALECT="${DB_DIALECT}" \
            --env DB_PORT="${DB_PORT}" \
            --env FRONTEND_DOMAIN="${FRONTEND_DOMAIN}" \
            --env VERSION="${VERSION}" \
            --env JWT_SECRET_KEY="${JWT_SECRET_KEY}" \
            --env JWT_DURATION="${JWT_DURATION}" \
            --env GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}" \
            --env GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}" \
            --env SGID_CLIENT_ID="${SGID_CLIENT_ID}"\
            --env SGID_CLIENT_SECRET="${SGID_CLIENT_SECRET}"\
            --env SGID_PRIVATE_KEY="${SGID_PRIVATE_KEY}"\
            --env TZ="${BACKEND_TZ}" \
            --env BACKEND_DOMAIN="${BACKEND_DOMAIN}" \
            --env STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY}" \
            -c ./apps/backend/.fly/fly.toml --local-only .
